In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the Iris dataset
data = pd.read_csv(r"C:\Users\lenovo\Downloads\iris.csv")

In [3]:
# Select numeric columns for computing the covariance matrix
# Assuming the columns are the standard Iris dataset features: 'sepal_length', 'sepal_width', 'petal_length', 'petal_width'
features = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

In [9]:
# Step 1: Compute the covariance matrix
cov_matrix = np.cov(features.T)
print("Covariance Matrix:\n", cov_matrix)


Covariance Matrix:
 [[ 0.68569351 -0.03926846  1.27368233  0.5169038 ]
 [-0.03926846  0.18800403 -0.32171275 -0.11798121]
 [ 1.27368233 -0.32171275  3.11317942  1.29638747]
 [ 0.5169038  -0.11798121  1.29638747  0.58241432]]


In [10]:
# Step 2: Perform eigen decomposition to obtain eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [4.22484077 0.24224357 0.07852391 0.02368303]

Eigenvectors:
 [[ 0.36158968 -0.65653988 -0.58099728  0.31725455]
 [-0.08226889 -0.72971237  0.59641809 -0.32409435]
 [ 0.85657211  0.1757674   0.07252408 -0.47971899]
 [ 0.35884393  0.07470647  0.54906091  0.75112056]]


In [11]:
# Step 3: Form the diagonal matrix D using the eigenvalues
D = np.diag(eigenvalues)
print("\nDiagonal Matrix D:\n", D)


Diagonal Matrix D:
 [[4.22484077 0.         0.         0.        ]
 [0.         0.24224357 0.         0.        ]
 [0.         0.         0.07852391 0.        ]
 [0.         0.         0.         0.02368303]]


In [12]:
# Step 4: Calculate the inverse of D (only if it is invertible)
D_inv = np.linalg.inv(D) if np.all(eigenvalues) else None  # Check for zero eigenvalues
print("\nInverse of D:\n", D_inv if D_inv is not None else "D is not invertible (contains zero eigenvalues)")


Inverse of D:
 [[ 0.23669531  0.          0.          0.        ]
 [ 0.          4.12807652  0.          0.        ]
 [ 0.          0.         12.73497492  0.        ]
 [ 0.          0.          0.         42.22433199]]
